namespace HaYTooLWeather.Services;

/// <summary>
/// 7 dilde (TR, EN, ES, DE, PT, AR, RU) dinamik yerelleştirme servisi.
/// </summary>
public static class LocalizationService
{
    public static string CurrentLanguage { get; private set; } = "tr";

    public static readonly Dictionary<string, string> SupportedLanguages = new()
    {
        { "tr", "Türkçe (Turkish)" },
        { "en", "English" },
        { "es", "Español (Spanish)" },
        { "de", "Deutsch (German)" },
        { "pt", "Português (Portuguese)" },
        { "ar", "العربية (Arabic)" },
        { "ru", "Русский (Russian)" }
    };

    public static void SetLanguage(string langCode)
    {
        if (SupportedLanguages.ContainsKey(langCode.ToLowerInvariant()))
        {
            CurrentLanguage = langCode.ToLowerInvariant();
        }
        else
        {
            CurrentLanguage = "tr";
        }
    }

    public static string Get(string key)
    {
        if (_translations.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var text))
            return text;

        if (_translations["en"].TryGetValue(key, out var fallbackText))
            return fallbackText;

        return key;
    }

    /// <summary>
    /// WMO Hava Durumu Koduna (0-99) göre mevcut dilde açıklama döner.
    /// </summary>
    public static string GetWeatherDescription(int code)
    {
        return code switch
        {
            0 => Get("w_clear_sky"),
            1 => Get("w_mainly_clear"),
            2 => Get("w_partly_cloudy"),
            3 => Get("w_overcast"),
            45 => Get("w_fog"),
            48 => Get("w_depositing_rime_fog"),
            51 => Get("w_drizzle_light"),
            53 => Get("w_drizzle_moderate"),
            55 => Get("w_drizzle_dense"),
            56 => Get("w_freezing_drizzle_light"),
            57 => Get("w_freezing_drizzle_dense"),
            61 => Get("w_rain_slight"),
            62 or 63 => Get("w_rain_moderate"),
            65 => Get("w_rain_heavy"),
            66 => Get("w_freezing_rain_light"),
            67 => Get("w_freezing_rain_heavy"),
            71 => Get("w_snow_slight"),
            73 => Get("w_snow_moderate"),
            75 => Get("w_snow_heavy"),
            77 => Get("w_snow_grains"),
            80 => Get("w_rain_showers_slight"),
            81 => Get("w_rain_showers_moderate"),
            82 => Get("w_rain_showers_violent"),
            85 => Get("w_snow_showers_slight"),
            86 => Get("w_snow_showers_heavy"),
            95 => Get("w_thunderstorm"),
            96 => Get("w_thunderstorm_slight_hail"),
            99 => Get("w_thunderstorm_heavy_hail"),
            _ => Get("w_unknown")
        };
    }

    public static string GetDayName(DayOfWeek dayOfWeek)
    {
        return dayOfWeek switch
        {
            DayOfWeek.Monday => Get("day_mon"),
            DayOfWeek.Tuesday => Get("day_tue"),
            DayOfWeek.Wednesday => Get("day_wed"),
            DayOfWeek.Thursday => Get("day_thu"),
            DayOfWeek.Friday => Get("day_fri"),
            DayOfWeek.Saturday => Get("day_sat"),
            DayOfWeek.Sunday => Get("day_sun"),
            _ => dayOfWeek.ToString()
        };
    }

    private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["tr"] = new()
        {
            ["app_name"] = "HaYTooL Weather",
            ["menu_change_location"] = "Konum Değiştir / Ara...",
            ["menu_refresh_now"] = "Şimdi Güncelle",
            ["menu_detailed_forecast"] = "Detaylı Hava Durumu Kartı",
            ["menu_settings"] = "Ayarlar & Kontrol Merkezi",
            ["menu_language"] = "Dil (Language)",
            ["menu_about"] = "Hakkında",
            ["menu_exit"] = "Çıkış",
            ["updating"] = "Hava durumu güncelleniyor...",
            ["update_success"] = "Hava durumu başarıyla güncellendi.",
            ["update_error"] = "Hava durumu güncellenemedi.",
            ["humidity"] = "Nem",
            ["wind"] = "Rüzgar",
            ["feels_like"] = "Hissedilen",
            ["rain_chance"] = "Yağış İhtimali",
            ["today"] = "Bugün",
            ["hourly"] = "Saatlik Tahmin",
            ["daily_7"] = "7 Günlük Tahmin",
            ["last_update"] = "Son Güncelleme",
            ["settings_title"] = "Kontrol Merkezi & Ayarlar",
            ["tab_location"] = "📍  Konum & Şehir",
            ["tab_appearance"] = "🎨  Görünüm & Boyut",
            ["tab_general"] = "⚙️  Genel & Birimler",
            ["tab_language"] = "🌐  Dil / Language",
            ["tab_about"] = "ℹ️  Hakkında",
            ["loc_title"] = "📍 Konum & Şehir Yönetimi",
            ["loc_active_badge"] = "AKTİF SEÇİLİ KONUM",
            ["loc_popular"] = "⚡ Popüler Şehirler (1 Tıkla Anında Seç):",
            ["loc_search_title"] = "🔍 İl, İlçe veya Dünya Şehri Ara:",
            ["loc_search_placeholder"] = "Örn: Kadıköy, İzmit, Berlin, Tokyo...",
            ["loc_search_btn"] = "Ara",
            ["loc_apply_btn"] = "✓ Seçili Konumu Uygula",
            ["loc_searching"] = "🔍 Aranıyor...",
            ["loc_no_results"] = "❌ Sonuç bulunamadı.",
            ["app_title"] = "🎨 Görev Çubuğu & Görünüm Ayarları",
            ["app_live_preview"] = "CANLI GÖREV ÇUBUĞU ÖNİZLEMESİ",
            ["app_mode"] = "Gösterim Modu:",
            ["app_weather_icon"] = "🌤️ Hava Durumu Simgesi",
            ["app_temp_text"] = "🌡️ Sıcaklık Derecesi",
            ["app_icon_size"] = "Simge Boyutu:",
            ["app_text_size"] = "Rakam Boyutu:",
            ["app_bg_color"] = "Arka Plan Rengi:",
            ["app_bg_opacity"] = "Arka Plan Opaklığı:",
            ["app_pick_color"] = "Renk Seç...",
            ["app_high_contrast"] = "Yüksek Kontrastlı Beyaz Rakamlar",
            ["gen_title"] = "⚙️ Genel & Sistem Tercihleri",
            ["gen_weather_provider"] = "📡 Hava Durumu Veri Kaynağı / Tahmin Modeli:",
            ["provider_auto"] = "🌟 Otomatik (Varsayılan - En İyi Eşleşme)",
            ["provider_mgm"] = "🇹🇷 Resmi Türkiye Meteorolojisi (MGM - mgm.gov.tr)",
            ["provider_ecmwf"] = "🇪🇺 Avrupa Tahmin Modeli (ECMWF IFS)",
            ["provider_gfs"] = "🇺🇸 Amerika Tahmin Modeli (GFS / NOAA)",
            ["provider_dwd"] = "🇩🇪 Almanya Tahmin Modeli (DWD ICON)",
            ["gen_update_interval"] = "🔄 Hava Durumu Güncelleme Sıklığı:",
            ["gen_temp_unit"] = "🌡️ Sıcaklık Birimi:",
            ["gen_wind_unit"] = "💨 Rüzgar Hızı Birimi:",
            ["gen_autostart"] = "Windows Başlangıcında Otomatik Başlat",
            ["gen_auto_check_updates"] = "🔄 Başlangıçta Otomatik Güncellemeleri Denetle",
            ["about_header"] = "ℹ️ HaYTooL Weather Hakkında",
            ["about_ver"] = "Sürüm {0} - Windows Native Desktop Application",
            ["about_dev"] = "Geliştirici: HaYTo",
            ["about_contact"] = "İletişim:",
            ["about_copy"] = "© 2026 HaYTo. Tüm Hakları Saklıdır. MIT Lisansı.",
            ["status_on"] = "[ AÇIK ]",
            ["status_off"] = "[ KAPALI ]",
            ["about_check_updates"] = "🔄 Güncellemeleri Denetle",
            ["about_checking_updates"] = "🔍 Güncellemeler denetleniyor...",
            ["about_latest_version"] = "✓ En güncel sürümü kullanıyorsunuz! ({0})",
            ["about_update_available"] = "🚀 Yeni sürüm mevcut: {0}",
            ["about_update_btn"] = "⬇️ İndirme Sayfasını Aç",
            ["notify_update_title"] = "🚀 Yeni Sürüm Mevcut! ({0})",
            ["notify_update_body"] = "HaYTooL Weather {0} yayınlandı. İndirmek için tıklayın.",
            ["btn_close"] = "✓ Tamam / Kapat",
            ["hours_1"] = "1 Saat",
            ["hours_3"] = "3 Saat",
            ["hours_6"] = "6 Saat (Varsayılan)",
            ["hours_12"] = "12 Saat",
            ["hours_24"] = "24 Saat",
            ["min_30"] = "30 Dakika",
            ["day_mon"] = "Pzt", ["day_tue"] = "Sal", ["day_wed"] = "Çar", ["day_thu"] = "Per", ["day_fri"] = "Cum", ["day_sat"] = "Cmt", ["day_sun"] = "Paz",
            ["w_clear_sky"] = "Açık",
            ["w_mainly_clear"] = "Çoğunlukla Açık",
            ["w_partly_cloudy"] = "Parçalı Bulutlu",
            ["w_overcast"] = "Kapalı / Bulutlu",
            ["w_fog"] = "Sisli",
            ["w_depositing_rime_fog"] = "Kırağılı Sis",
            ["w_drizzle_light"] = "Hafif Çisenti",
            ["w_drizzle_moderate"] = "Çisenti",
            ["w_drizzle_dense"] = "Yoğun Çisenti",
            ["w_freezing_drizzle_light"] = "Hafif Dondurucu Çisenti",
            ["w_freezing_drizzle_dense"] = "Yoğun Dondurucu Çisenti",
            ["w_rain_slight"] = "Hafif Yağmurlu",
            ["w_rain_moderate"] = "Yağmurlu",
            ["w_rain_heavy"] = "Kuvvetli Yağmur",
            ["w_freezing_rain_light"] = "Hafif Dondurucu Yağmur",
            ["w_freezing_rain_heavy"] = "Kuvvetli Dondurucu Yağmur",
            ["w_snow_slight"] = "Hafif Karlı",
            ["w_snow_moderate"] = "Karlı",
            ["w_snow_heavy"] = "Yoğun Kar Yağışlı",
            ["w_snow_grains"] = "Kar Taneleri",
            ["w_rain_showers_slight"] = "Hafif Sağanak",
            ["w_rain_showers_moderate"] = "Sağanak Yağışlı",
            ["w_rain_showers_violent"] = "Şiddetli Sağanak",
            ["w_snow_showers_slight"] = "Hafif Kar Sağanağı",
            ["w_snow_showers_heavy"] = "Kuvvetli Kar Sağanağı",
            ["w_thunderstorm"] = "Gök Gürültülü Fırtına",
            ["w_thunderstorm_slight_hail"] = "Hafif Dolulu Fırtına",
            ["w_thunderstorm_heavy_hail"] = "Şiddetli Dolulu Fırtına",
            ["w_unknown"] = "Bilinmiyor"
        },
        ["en"] = new()
        {
            ["app_name"] = "HaYTooL Weather",
            ["menu_change_location"] = "Change Location / Search...",
            ["menu_refresh_now"] = "Refresh Now",
            ["menu_detailed_forecast"] = "Detailed Forecast Card",
            ["menu_settings"] = "Settings & Control Center",
            ["menu_language"] = "Language",
            ["menu_about"] = "About",
            ["menu_exit"] = "Exit",
            ["updating"] = "Updating weather...",
            ["update_success"] = "Weather updated successfully.",
            ["update_error"] = "Failed to update weather.",
            ["humidity"] = "Humidity",
            ["wind"] = "Wind",
            ["feels_like"] = "Feels Like",
            ["rain_chance"] = "Rain Chance",
            ["today"] = "Today",
            ["hourly"] = "Hourly Forecast",
            ["daily_7"] = "7-Day Forecast",
            ["last_update"] = "Last Updated",
            ["settings_title"] = "Control Center & Settings",
            ["tab_location"] = "📍  Location & City",
            ["tab_appearance"] = "🎨  Appearance & Size",
            ["tab_general"] = "⚙️  General & Units",
            ["tab_language"] = "🌐  Language / Dil",
            ["tab_about"] = "ℹ️  About",
            ["loc_title"] = "📍 Location & City Management",
            ["loc_active_badge"] = "ACTIVE SELECTED LOCATION",
            ["loc_popular"] = "⚡ Popular Cities (1-Click Instant):",
            ["loc_search_title"] = "🔍 Search City, District or Worldwide:",
            ["loc_search_placeholder"] = "e.g. London, New York, Berlin, Tokyo...",
            ["loc_search_btn"] = "Search",
            ["loc_apply_btn"] = "✓ Apply Selected Location",
            ["loc_searching"] = "🔍 Searching...",
            ["loc_no_results"] = "❌ No results found.",
            ["app_title"] = "🎨 Taskbar & Appearance Settings",
            ["app_live_preview"] = "LIVE TASKBAR PREVIEW",
            ["app_mode"] = "Display Mode:",
            ["app_weather_icon"] = "🌤️ Weather Icon",
            ["app_temp_text"] = "🌡️ Temperature Text",
            ["app_icon_size"] = "Icon Size:",
            ["app_text_size"] = "Text Size:",
            ["app_bg_color"] = "Background Color:",
            ["app_bg_opacity"] = "Background Opacity:",
            ["app_pick_color"] = "Pick Color...",
            ["app_high_contrast"] = "High Contrast White Digits",
            ["gen_title"] = "⚙️ General & System Preferences",
            ["gen_weather_provider"] = "📡 Weather Data Provider / Forecast Model:",
            ["provider_auto"] = "🌟 Automatic (Default - Best Match)",
            ["provider_mgm"] = "🇹🇷 Turkish State Meteorological Service (MGM)",
            ["provider_ecmwf"] = "🇪🇺 European Forecast Model (ECMWF IFS)",
            ["provider_gfs"] = "🇺🇸 US Forecast Model (GFS / NOAA)",
            ["provider_dwd"] = "🇩🇪 German Forecast Model (DWD ICON)",
            ["gen_update_interval"] = "🔄 Weather Update Interval:",
            ["gen_temp_unit"] = "🌡️ Temperature Unit:",
            ["gen_wind_unit"] = "💨 Wind Speed Unit:",
            ["gen_autostart"] = "Start Automatically with Windows",
            ["gen_auto_check_updates"] = "🔄 Automatically Check for Updates on Startup",
            ["about_header"] = "ℹ️ About HaYTooL Weather",
            ["about_ver"] = "Version {0} - Windows Native Desktop Application",
            ["about_dev"] = "Developer: HaYTo",
            ["about_contact"] = "Contact:",
            ["about_copy"] = "© 2026 HaYTo. All Rights Reserved. MIT License.",
            ["status_on"] = "[ ON ]",
            ["status_off"] = "[ OFF ]",
            ["about_check_updates"] = "🔄 Check for Updates",
            ["about_checking_updates"] = "🔍 Checking for updates...",
            ["about_latest_version"] = "✓ You are using the latest version! ({0})",
            ["about_update_available"] = "🚀 New version available: {0}",
            ["about_update_btn"] = "⬇️ Open Download Page",
            ["notify_update_title"] = "🚀 New Version Available! ({0})",
            ["notify_update_body"] = "HaYTooL Weather {0} is available. Click to download.",
            ["btn_close"] = "✓ Done / Close",
            ["hours_1"] = "1 Hour",
            ["hours_3"] = "3 Hours",
            ["hours_6"] = "6 Hours (Default)",
            ["hours_12"] = "12 Hours",
            ["hours_24"] = "24 Hours",
            ["min_30"] = "30 Minutes",
            ["day_mon"] = "Mon", ["day_tue"] = "Tue", ["day_wed"] = "Wed", ["day_thu"] = "Thu", ["day_fri"] = "Fri", ["day_sat"] = "Sat", ["day_sun"] = "Sun",
            ["w_clear_sky"] = "Clear Sky",
            ["w_mainly_clear"] = "Mainly Clear",
            ["w_partly_cloudy"] = "Partly Cloudy",
            ["w_overcast"] = "Overcast",
            ["w_fog"] = "Foggy",
            ["w_depositing_rime_fog"] = "Depositing Rime Fog",
            ["w_drizzle_light"] = "Light Drizzle",
            ["w_drizzle_moderate"] = "Moderate Drizzle",
            ["w_drizzle_dense"] = "Dense Drizzle",
            ["w_freezing_drizzle_light"] = "Light Freezing Drizzle",
            ["w_freezing_drizzle_dense"] = "Dense Freezing Drizzle",
            ["w_rain_slight"] = "Slight Rain",
            ["w_rain_moderate"] = "Moderate Rain",
            ["w_rain_heavy"] = "Heavy Rain",
            ["w_freezing_rain_light"] = "Light Freezing Rain",
            ["w_freezing_rain_heavy"] = "Heavy Freezing Rain",
            ["w_snow_slight"] = "Slight Snow",
            ["w_snow_moderate"] = "Moderate Snow",
            ["w_snow_heavy"] = "Heavy Snow",
            ["w_snow_grains"] = "Snow Grains",
            ["w_rain_showers_slight"] = "Slight Rain Showers",
            ["w_rain_showers_moderate"] = "Moderate Rain Showers",
            ["w_rain_showers_violent"] = "Violent Rain Showers",
            ["w_snow_showers_slight"] = "Slight Snow Showers",
            ["w_snow_showers_heavy"] = "Heavy Snow Showers",
            ["w_thunderstorm"] = "Thunderstorm",
            ["w_thunderstorm_slight_hail"] = "Thunderstorm with Slight Hail",
            ["w_thunderstorm_heavy_hail"] = "Thunderstorm with Heavy Hail",
            ["w_unknown"] = "Unknown"
        },
        ["de"] = new()
        {
            ["app_name"] = "HaYTooL Weather",
            ["menu_change_location"] = "Standort ändern...",
            ["menu_refresh_now"] = "Jetzt aktualisieren",
            ["menu_detailed_forecast"] = "Detaillierte Wetterkarte",
            ["menu_settings"] = "Einstellungen & Kontrollzentrum",
            ["menu_language"] = "Sprache",
            ["menu_about"] = "Über",
            ["menu_exit"] = "Beenden",
            ["settings_title"] = "Kontrollzentrum & Einstellungen",
            ["tab_location"] = "📍  Standort & Stadt",
            ["tab_appearance"] = "🎨  Erscheinungsbild",
            ["tab_general"] = "⚙️  Allgemein",
            ["tab_language"] = "🌐  Sprache",
            ["tab_about"] = "ℹ️  Über",
            ["loc_title"] = "📍 Standortverwaltung",
            ["loc_active_badge"] = "AKTIVER STANDORT",
            ["loc_popular"] = "⚡ Beliebte Städte:",
            ["loc_search_title"] = "🔍 Stadt suchen:",
            ["loc_search_placeholder"] = "z.B. Berlin, München, Hamburg...",
            ["loc_search_btn"] = "Suchen",
            ["loc_apply_btn"] = "✓ Standort anwenden",
            ["app_title"] = "🎨 Taskleiste & Erscheinungsbild",
            ["app_live_preview"] = "TASKLEISTEN-VORSCHAU",
            ["app_mode"] = "Anzeigemodus:",
            ["app_weather_icon"] = "🌤️ Wettersymbol",
            ["app_temp_text"] = "🌡️ Temperaturanzeige",
            ["app_icon_size"] = "Symbolgröße:",
            ["app_text_size"] = "Schriftgröße:",
            ["app_bg_color"] = "Hintergrundfarbe:",
            ["app_bg_opacity"] = "Deckkraft:",
            ["app_pick_color"] = "Farbe wählen...",
            ["app_high_contrast"] = "Hoher Kontrast (Weiß)",
            ["gen_title"] = "⚙️ Systemeinstellungen",
            ["gen_weather_provider"] = "📡 Wetterdatenquelle / Vorhersagemodell:",
            ["provider_auto"] = "🌟 Automatisch (Standard - Bester Treffer)",
            ["provider_mgm"] = "🇹🇷 Türkischer Wetterdienst (MGM)",
            ["provider_ecmwf"] = "🇪🇺 Europäisches Modell (ECMWF IFS)",
            ["provider_gfs"] = "🇺🇸 US-Modell (GFS / NOAA)",
            ["provider_dwd"] = "🇩🇪 Deutsches Modell (DWD ICON)",
            ["gen_update_interval"] = "🔄 Aktualisierungsintervall:",
            ["gen_temp_unit"] = "🌡️ Temperatureinheit:",
            ["gen_wind_unit"] = "💨 Windgeschwindigkeit:",
            ["gen_autostart"] = "Mit Windows starten",
            ["gen_auto_check_updates"] = "🔄 Beim Start automatisch nach Updates suchen",
            ["about_header"] = "ℹ️ Über HaYTooL Weather",
            ["about_ver"] = "Version {0} - Windows Native",
            ["about_dev"] = "Entwickler: HaYTo",
            ["about_contact"] = "Kontakt:",
            ["about_copy"] = "© 2026 HaYTo. Alle Rechte vorbehalten.",
            ["status_on"] = "[ EIN ]",
            ["status_off"] = "[ AUS ]",
            ["about_check_updates"] = "🔄 Nach Updates suchen",
            ["about_checking_updates"] = "🔍 Suche nach Updates...",
            ["about_latest_version"] = "✓ Sie verwenden die neueste Version! ({0})",
            ["about_update_available"] = "🚀 Neue Version verfügbar: {0}",
            ["about_update_btn"] = "⬇️ Download-Seite öffnen",
            ["notify_update_title"] = "🚀 Neue Version verfügbar! ({0})",
            ["notify_update_body"] = "HaYTooL Weather {0} ist verfügbar. Klicken zum Herunterladen.",
            ["btn_close"] = "✓ Schließen",
            ["hours_1"] = "1 Stunde",
            ["hours_3"] = "3 Stunden",
            ["hours_6"] = "6 Stunden",
            ["hours_12"] = "12 Stunden",
            ["hours_24"] = "24 Stunden",
            ["min_30"] = "30 Minuten",
            ["day_mon"] = "Mo", ["day_tue"] = "Di", ["day_wed"] = "Mi", ["day_thu"] = "Do", ["day_fri"] = "Fr", ["day_sat"] = "Sa", ["day_sun"] = "So",
            ["w_clear_sky"] = "Klarer Himmel",
            ["w_mainly_clear"] = "Überwiegend klar",
            ["w_partly_cloudy"] = "Teilweise bewölkt",
            ["w_overcast"] = "Bedeckt",
            ["w_fog"] = "Nebel",
            ["w_rain_slight"] = "Leichter Regen",
            ["w_rain_moderate"] = "Regen",
            ["w_rain_heavy"] = "Starker Regen",
            ["w_snow_slight"] = "Leichter Schneefall",
            ["w_thunderstorm"] = "Gewitter",
            ["w_unknown"] = "Unbekannt"
        },
        ["es"] = new()
        {
            ["app_name"] = "HaYTooL Weather",
            ["menu_change_location"] = "Cambiar ubicación...",
            ["menu_refresh_now"] = "Actualizar ahora",
            ["menu_detailed_forecast"] = "Tarjeta detallada",
            ["menu_settings"] = "Ajustes & Panel de control",
            ["menu_language"] = "Idioma",
            ["menu_about"] = "Acerca de",
            ["menu_exit"] = "Salir",
            ["settings_title"] = "Panel de control & Ajustes",
            ["tab_location"] = "📍  Ubicación & Ciudad",
            ["tab_appearance"] = "🎨  Apariencia & Tamaño",
            ["tab_general"] = "⚙️  General & Unidades",
            ["tab_language"] = "🌐  Idioma",
            ["tab_about"] = "ℹ️  Acerca de",
            ["loc_title"] = "📍 Gestión de Ubicación",
            ["loc_active_badge"] = "UBICACIÓN ACTIVA",
            ["loc_popular"] = "⚡ Ciudades Populares:",
            ["loc_search_title"] = "🔍 Buscar Ciudad:",
            ["loc_search_placeholder"] = "Ej: Madrid, Barcelona, Valencia...",
            ["loc_search_btn"] = "Buscar",
            ["loc_apply_btn"] = "✓ Aplicar Ubicación",
            ["app_title"] = "🎨 Configuración de Apariencia",
            ["app_live_preview"] = "VISTA PREVIA EN BARRA DE TAREAS",
            ["app_mode"] = "Modo de visualización:",
            ["app_weather_icon"] = "🌤️ Icono del Clima",
            ["app_temp_text"] = "🌡️ Texto de Temperatura",
            ["app_icon_size"] = "Tamaño del Icono:",
            ["app_text_size"] = "Tamaño del Texto:",
            ["app_bg_color"] = "Color de Fondo:",
            ["app_bg_opacity"] = "Opacidad de Fondo:",
            ["app_pick_color"] = "Elegir Color...",
            ["app_high_contrast"] = "Alto Contraste (Blanco)",
            ["gen_title"] = "⚙️ Preferencias del Sistema",
            ["gen_weather_provider"] = "📡 Proveedor de Datos / Modelo Meteorológico:",
            ["provider_auto"] = "🌟 Automático (Predeterminado - Mejor Ajuste)",
            ["provider_mgm"] = "🇹🇷 Servicio Meteorológico de Turquía (MGM)",
            ["provider_ecmwf"] = "🇪🇺 Modelo Europeo (ECMWF IFS)",
            ["provider_gfs"] = "🇺🇸 Modelo de EE. UU. (GFS / NOAA)",
            ["provider_dwd"] = "🇩🇪 Modelo Alemán (DWD ICON)",
            ["gen_update_interval"] = "🔄 Intervalo de actualización:",
            ["gen_temp_unit"] = "🌡️ Unidad de Temperatura:",
            ["gen_wind_unit"] = "💨 Unidad de Viento:",
            ["gen_autostart"] = "Iniciar con Windows",
            ["gen_auto_check_updates"] = "🔄 Buscar actualizaciones automáticamente al iniciar",
            ["about_header"] = "ℹ️ Acerca de HaYTooL Weather",
            ["about_ver"] = "Versión {0} - Windows Native",
            ["about_dev"] = "Desarrollador: HaYTo",
            ["about_contact"] = "Contacto:",
            ["about_copy"] = "© 2026 HaYTo. Todos los derechos reservados.",
            ["status_on"] = "[ ACTIVADO ]",
            ["status_off"] = "[ DESACTIVADO ]",
            ["about_check_updates"] = "🔄 Buscar actualizaciones",
            ["about_checking_updates"] = "🔍 Buscando actualizaciones...",
            ["about_latest_version"] = "✓ ¡Estás usando la última versión! ({0})",
            ["about_update_available"] = "🚀 Nueva versión disponible: {0}",
            ["about_update_btn"] = "⬇️ Abrir página de descarga",
            ["notify_update_title"] = "🚀 ¡Nueva versión disponible! ({0})",
            ["notify_update_body"] = "HaYTooL Weather {0} está disponible. Haz clic para descargar.",
            ["btn_close"] = "✓ Cerrar",
            ["hours_1"] = "1 Hora",
            ["hours_3"] = "3 Horas",
            ["hours_6"] = "6 Horas",
            ["hours_12"] = "12 Horas",
            ["hours_24"] = "24 Horas",
            ["min_30"] = "30 Minutos",
            ["day_mon"] = "Lun", ["day_tue"] = "Mar", ["day_wed"] = "Mié", ["day_thu"] = "Jue", ["day_fri"] = "Vie", ["day_sat"] = "Sáb", ["day_sun"] = "Dom",
            ["w_clear_sky"] = "Cielo despejado",
            ["w_mainly_clear"] = "Mayormente despejado",
            ["w_partly_cloudy"] = "Parcialmente nublado",
            ["w_overcast"] = "Nublado",
            ["w_fog"] = "Niebla",
            ["w_rain_slight"] = "Lluvia ligera",
            ["w_rain_moderate"] = "Lluvia",
            ["w_rain_heavy"] = "Lluvia fuerte",
            ["w_snow_slight"] = "Nieve ligera",
            ["w_thunderstorm"] = "Tormenta",
            ["w_unknown"] = "Desconocido"
        },
        ["pt"] = new()
        {
            ["app_name"] = "HaYTooL Weather",
            ["menu_change_location"] = "Alterar Localização...",
            ["menu_refresh_now"] = "Atualizar Agora",
            ["menu_detailed_forecast"] = "Previsão Detalhada",
            ["menu_settings"] = "Configurações & Painel",
            ["menu_language"] = "Idioma",
            ["menu_about"] = "Sobre",
            ["menu_exit"] = "Sair",
            ["settings_title"] = "Painel de Controle & Configurações",
            ["tab_location"] = "📍  Localização & Cidade",
            ["tab_appearance"] = "🎨  Aparência & Tamanho",
            ["tab_general"] = "⚙️  Geral & Unidades",
            ["tab_language"] = "🌐  Idioma",
            ["tab_about"] = "ℹ️  Sobre",
            ["loc_title"] = "📍 Gestão de Localização",
            ["loc_active_badge"] = "LOCALIZAÇÃO ATIVA",
            ["loc_popular"] = "⚡ Cidades Populares:",
            ["loc_search_title"] = "🔍 Procurar Cidade:",
            ["loc_search_placeholder"] = "Ex: Lisboa, Porto, São Paulo...",
            ["loc_search_btn"] = "Procurar",
            ["loc_apply_btn"] = "✓ Aplicar Localização",
            ["app_title"] = "🎨 Configurações de Aparência",
            ["app_live_preview"] = "PRÉ-VISUALIZAÇÃO DA BARRA",
            ["app_mode"] = "Modo de exibição:",
            ["app_weather_icon"] = "🌤️ Ícone do Tempo",
            ["app_temp_text"] = "🌡️ Texto de Temperatura",
            ["app_icon_size"] = "Tamanho do Ícone:",
            ["app_text_size"] = "Tamanho do Texto:",
            ["app_bg_color"] = "Cor de Fundo:",
            ["app_bg_opacity"] = "Opacidade:",
            ["app_pick_color"] = "Escolher Cor...",
            ["app_high_contrast"] = "Alto Contraste (Branco)",
            ["gen_title"] = "⚙️ Preferências do Sistema",
            ["gen_weather_provider"] = "📡 Provedor de Dados / Modelo Meteorológico:",
            ["provider_auto"] = "🌟 Automático (Padrão - Melhor Combinação)",
            ["provider_mgm"] = "🇹🇷 Serviço Meteorológico Turco (MGM)",
            ["provider_ecmwf"] = "🇪🇺 Modelo Europeu (ECMWF IFS)",
            ["provider_gfs"] = "🇺🇸 Modelo dos EUA (GFS / NOAA)",
            ["provider_dwd"] = "🇩🇪 Modelo Alemão (DWD ICON)",
            ["gen_update_interval"] = "🔄 Intervalo de atualização:",
            ["gen_temp_unit"] = "🌡️ Unidade de Temperatura:",
            ["gen_wind_unit"] = "💨 Unidade de Vento:",
            ["gen_autostart"] = "Iniciar com o Windows",
            ["gen_auto_check_updates"] = "🔄 Verificar atualizações automaticamente ao iniciar",
            ["about_header"] = "ℹ️ Sobre HaYTooL Weather",
            ["about_ver"] = "Versão {0} - Windows Native",
            ["about_dev"] = "Desenvolvedor: HaYTo",
            ["about_contact"] = "Contato:",
            ["about_copy"] = "© 2026 HaYTo. Todos os direitos reservados.",
            ["status_on"] = "[ ATIVADO ]",
            ["status_off"] = "[ DESATIVADO ]",
            ["about_check_updates"] = "🔄 Verificar atualizações",
            ["about_checking_updates"] = "🔍 Verificando atualizações...",
            ["about_latest_version"] = "✓ Você está usando a versão mais recente! ({0})",
            ["about_update_available"] = "🚀 Nova versão disponível: {0}",
            ["about_update_btn"] = "⬇️ Abrir página de download",
            ["notify_update_title"] = "🚀 Nova versão disponível! ({0})",
            ["notify_update_body"] = "HaYTooL Weather {0} está disponível. Clique para baixar.",
            ["btn_close"] = "✓ Fechar",
            ["hours_1"] = "1 Hora",
            ["hours_3"] = "3 Horas",
            ["hours_6"] = "6 Horas",
            ["hours_12"] = "12 Horas",
            ["hours_24"] = "24 Horas",
            ["min_30"] = "30 Minutos",
            ["day_mon"] = "Seg", ["day_tue"] = "Ter", ["day_wed"] = "Qua", ["day_thu"] = "Qui", ["day_fri"] = "Sex", ["day_sat"] = "Sáb", ["day_sun"] = "Dom",
            ["w_clear_sky"] = "Céu limpo",
            ["w_mainly_clear"] = "Predominantemente limpo",
            ["w_partly_cloudy"] = "Parcialmente nublado",
            ["w_overcast"] = "Encoberto",
            ["w_fog"] = "Nevoeiro",
            ["w_rain_slight"] = "Chuva fraca",
            ["w_rain_moderate"] = "Chuva",
            ["w_rain_heavy"] = "Chuva forte",
            ["w_snow_slight"] = "Neve fraca",
            ["w_thunderstorm"] = "Trovoada",
            ["w_unknown"] = "Desconhecido"
        },
        ["ru"] = new()
        {
            ["app_name"] = "HaYTooL Weather",
            ["menu_change_location"] = "Сменить город...",
            ["menu_refresh_now"] = "Обновить сейчас",
            ["menu_detailed_forecast"] = "Подробный прогноз",
            ["menu_settings"] = "Настройки & Центр",
            ["menu_language"] = "Язык",
            ["menu_about"] = "О программе",
            ["menu_exit"] = "Выход",
            ["settings_title"] = "Центр управления & Настройки",
            ["tab_location"] = "📍  Город & Локация",
            ["tab_appearance"] = "🎨  Вид & Размер",
            ["tab_general"] = "⚙️  Общие & Единицы",
            ["tab_language"] = "🌐  Язык / Language",
            ["tab_about"] = "ℹ️  О программе",
            ["loc_title"] = "📍 Выбор города и локации",
            ["loc_active_badge"] = "ТЕКУЩИЙ ГОРОД",
            ["loc_popular"] = "⚡ Популярные города:",
            ["loc_search_title"] = "🔍 Поиск города / района:",
            ["loc_search_placeholder"] = "Например: Москва, Стамбул, Берлин...",
            ["loc_search_btn"] = "Найти",
            ["loc_apply_btn"] = "✓ Применить город",
            ["app_title"] = "🎨 Внешний вид панели задач",
            ["app_live_preview"] = "ПРЕДПРОСМОТР В ПАНЕЛИ",
            ["app_mode"] = "Режим отображения:",
            ["app_weather_icon"] = "🌤️ Значок погоды",
            ["app_temp_text"] = "🌡️ Температура",
            ["app_icon_size"] = "Размер значка:",
            ["app_text_size"] = "Размер шрифта:",
            ["app_bg_color"] = "Цвет фона:",
            ["app_bg_opacity"] = "Прозрачность:",
            ["app_pick_color"] = "Выбрать цвет...",
            ["app_high_contrast"] = "Высокая контрастность (Белый)",
            ["gen_title"] = "⚙️ Системные настройки",
            ["gen_weather_provider"] = "📡 Источник данных / Модель прогноза:",
            ["provider_auto"] = "🌟 Автоматически (По умолчанию)",
            ["provider_mgm"] = "🇹🇷 Гос. метеослужба Турции (MGM)",
            ["provider_ecmwf"] = "🇪🇺 Европейская модель (ECMWF IFS)",
            ["provider_gfs"] = "🇺🇸 Американская модель (GFS / NOAA)",
            ["provider_dwd"] = "🇩🇪 Немецкая модель (DWD ICON)",
            ["gen_update_interval"] = "🔄 Интервал обновления:",
            ["gen_temp_unit"] = "🌡️ Единица температуры:",
            ["gen_wind_unit"] = "💨 Единица скорости ветра:",
            ["gen_autostart"] = "Автозапуск при старте Windows",
            ["gen_auto_check_updates"] = "🔄 Автоматически проверять обновления при запуске",
            ["about_header"] = "ℹ️ О программе HaYTooL Weather",
            ["about_ver"] = "Версия {0} - Windows Native",
            ["about_dev"] = "Разработчик: HaYTo",
            ["about_contact"] = "Контакты:",
            ["about_copy"] = "© 2026 HaYTo. Все права защищены.",
            ["status_on"] = "[ ВКЛ ]",
            ["status_off"] = "[ ВЫКЛ ]",
            ["about_check_updates"] = "🔄 Проверить обновления",
            ["about_checking_updates"] = "🔍 Проверка обновлений...",
            ["about_latest_version"] = "✓ Вы используете последнюю версию! ({0})",
            ["about_update_available"] = "🚀 Доступна новая версия: {0}",
            ["about_update_btn"] = "⬇️ Открыть страницу загрузки",
            ["notify_update_title"] = "🚀 Доступна новая версия! ({0})",
            ["notify_update_body"] = "Вышла HaYTooL Weather {0}. Нажмите для загрузки.",
            ["btn_close"] = "✓ Закрыть",
            ["hours_1"] = "1 Час",
            ["hours_3"] = "3 Часа",
            ["hours_6"] = "6 Часов",
            ["hours_12"] = "12 Часов",
            ["hours_24"] = "24 Часа",
            ["min_30"] = "30 Минут",
            ["day_mon"] = "Пн", ["day_tue"] = "Вт", ["day_wed"] = "Ср", ["day_thu"] = "Чт", ["day_fri"] = "Пт", ["day_sat"] = "Сб", ["day_sun"] = "Вс",
            ["w_clear_sky"] = "Ясно",
            ["w_mainly_clear"] = "В основном ясно",
            ["w_partly_cloudy"] = "Переменная облачность",
            ["w_overcast"] = "Пасмурно",
            ["w_fog"] = "Туман",
            ["w_rain_slight"] = "Небольшой дождь",
            ["w_rain_moderate"] = "Дождь",
            ["w_rain_heavy"] = "Сильный дождь",
            ["w_snow_slight"] = "Небольшой снег",
            ["w_thunderstorm"] = "Гроза",
            ["w_unknown"] = "Неизвестно"
        },
        ["ar"] = new()
        {
            ["app_name"] = "HaYTooL Weather",
            ["menu_change_location"] = "تغيير الموقع...",
            ["menu_refresh_now"] = "تحديث الآن",
            ["menu_detailed_forecast"] = "بطاقة الطقس التفصيلية",
            ["menu_settings"] = "الإعدادات ومركز التحكم",
            ["menu_language"] = "اللغة",
            ["menu_about"] = "حول",
            ["menu_exit"] = "خروج",
            ["settings_title"] = "مركز التحكم والإعدادات",
            ["tab_location"] = "📍  الموقع والمدينة",
            ["tab_appearance"] = "🎨  المظهر والحجم",
            ["tab_general"] = "⚙️  عام والوحدات",
            ["tab_language"] = "🌐  اللغة",
            ["tab_about"] = "ℹ️  حول",
            ["loc_title"] = "📍 إدارة الموقع والمدينة",
            ["loc_active_badge"] = "الموقع المحدد حالياً",
            ["loc_popular"] = "⚡ المدن الشائعة:",
            ["loc_search_title"] = "🔍 ابحث عن مدينة:",
            ["loc_search_placeholder"] = "مثال: إسطنبول، الرياض، برلين...",
            ["loc_search_btn"] = "بحث",
            ["loc_apply_btn"] = "✓ تطبيق الموقع المحدد",
            ["app_title"] = "🎨 إعدادات المظهر وشريط المهام",
            ["app_live_preview"] = "معاينة شريط المهام المباشرة",
            ["app_mode"] = "وضع العرض:",
            ["app_weather_icon"] = "🌤️ رمز الطقس",
            ["app_temp_text"] = "🌡️ درجة الحرارة",
            ["app_icon_size"] = "حجم الرمز:",
            ["app_text_size"] = "حجم النص:",
            ["app_bg_color"] = "لون الخلفية:",
            ["app_bg_opacity"] = "الشفافية:",
            ["app_pick_color"] = "اختر اللون...",
            ["app_high_contrast"] = "تباين عالي (أرقام بيضاء)",
            ["gen_title"] = "⚙️ تفضيلات النظام",
            ["gen_weather_provider"] = "📡 مصدر بيانات الطقس / نموذج التنبؤ:",
            ["provider_auto"] = "🌟 تلقائي (افتراضي - أفضل تطابق)",
            ["provider_mgm"] = "🇹🇷 الأرصad الجوية التركية الرسمية (MGM)",
            ["provider_ecmwf"] = "🇪🇺 النموذج الأوروبي (ECMWF IFS)",
            ["provider_gfs"] = "🇺🇸 النموذج الأمريكي (GFS / NOAA)",
            ["provider_dwd"] = "🇩🇪 النموذج الألماني (DWD ICON)",
            ["gen_update_interval"] = "🔄 تكرار التحديث:",
            ["gen_temp_unit"] = "🌡️ وحدة الحرارة:",
            ["gen_wind_unit"] = "💨 وحدة الرياح:",
            ["gen_autostart"] = "التشغيل التلقائي مع الويندوز",
            ["gen_auto_check_updates"] = "🔄 التحقق التلقائي من وجود تحديثات عند بدء التشغيل",
            ["about_header"] = "ℹ️ حول HaYTooL Weather",
            ["about_ver"] = "الإصدار {0} - تطبيق ويندوز الأصلي",
            ["about_dev"] = "المطور: HaYTo",
            ["about_contact"] = "الاتصال:",
            ["about_copy"] = "© 2026 HaYTo. جميع الحقوق محفوظة.",
            ["status_on"] = "[ مفعّل ]",
            ["status_off"] = "[ معطّل ]",
            ["about_check_updates"] = "🔄 التحقق من وجود تحديثات",
            ["about_checking_updates"] = "🔍 جارٍ التحقق من التحديثات...",
            ["about_latest_version"] = "✓ أنت تستخدم أحدث إصدار! ({0})",
            ["about_update_available"] = "🚀 يتوفر إصدار جديد: {0}",
            ["about_update_btn"] = "⬇️ فتح صفحة التنزيل",
            ["notify_update_title"] = "🚀 يتوفر إصدار جديد! ({0})",
            ["notify_update_body"] = "تم إصدار HaYTooL Weather {0}. انقر للتنزيل.",
            ["btn_close"] = "✓ إغلاق",
            ["hours_1"] = "ساعة واحدة",
            ["hours_3"] = "3 ساعات",
            ["hours_6"] = "6 ساعات",
            ["hours_12"] = "12 ساعة",
            ["hours_24"] = "24 ساعة",
            ["min_30"] = "30 دقيقة",
            ["day_mon"] = "الإثنين", ["day_tue"] = "الثلاثاء", ["day_wed"] = "الأربعاء", ["day_thu"] = "الخميس", ["day_fri"] = "الجمعة", ["day_sat"] = "السبت", ["day_sun"] = "الأحد",
            ["w_clear_sky"] = "سماء صافية",
            ["w_mainly_clear"] = "صافٍ غالباً",
            ["w_partly_cloudy"] = "غائم جزئياً",
            ["w_overcast"] = "غائم كلياً",
            ["w_fog"] = "ضباب",
            ["w_rain_slight"] = "مطر خفيف",
            ["w_rain_moderate"] = "مطر",
            ["w_rain_heavy"] = "مطر غزير",
            ["w_snow_slight"] = "ثلج خفيف",
            ["w_thunderstorm"] = "عاصفة رعدية",
            ["w_unknown"] = "غير معروف"
        }
    };
}
